export const data = [
  {
    id: 1,
    name: "Pizza",
    sale_items: [
      {
        id: 6,
        name: "Speciel Andha Burger",
        measurment_unit_id: 2,
        price: 180,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 9,
        name: "Zinger Burger",
        measurment_unit_id: 2,
        price: 300,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 11,
        name: "Zinger Burger jumboo",
        measurment_unit_id: 2,
        price: 450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 13,
        name: "Tower Burger",
        measurment_unit_id: 2,
        price: 650,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 14,
        name: "Zinger Shawarma",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 15,
        name: "Tika Shawarma",
        measurment_unit_id: 2,
        price: 270,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 17,
        name: "Pizza Shawarma",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 23,
        name: "Zinger Paratha",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 24,
        name: "Tika Paratha",
        measurment_unit_id: 2,
        price: 270,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 32,
        name: "Donner",
        measurment_unit_id: 2,
        price: 400,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 33,
        name: "Cheese Donner",
        measurment_unit_id: 2,
        price: 500,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 34,
        name: "Raap",
        measurment_unit_id: 2,
        price: 450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 35,
        name: "Cheese Raap",
        measurment_unit_id: 2,
        price: 550,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 37,
        name: "Tika Pizza S",
        measurment_unit_id: 2,
        price: 400,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 38,
        name: "Tika Pizza M",
        measurment_unit_id: 2,
        price: 900,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 39,
        name: "Tika Pizza L",
        measurment_unit_id: 2,
        price: 1200,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 40,
        name: "Fajita Pizza S",
        measurment_unit_id: 2,
        price: 400,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 41,
        name: "Fajita Pizza M",
        measurment_unit_id: 2,
        price: 900,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 42,
        name: "Fajita Pizza L",
        measurment_unit_id: 2,
        price: 1200,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 43,
        name: "Tika Pizza XL",
        measurment_unit_id: 2,
        price: 1800,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 44,
        name: "Fajita Pizza XL",
        measurment_unit_id: 2,
        price: 1800,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 45,
        name: "Malai Boti Pizza S",
        measurment_unit_id: 2,
        price: 450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 46,
        name: "Malai Boti Pizza M",
        measurment_unit_id: 2,
        price: 1000,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 47,
        name: "Malai Boti Pizza L",
        measurment_unit_id: 2,
        price: 1300,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 48,
        name: "Malai Boti Pizza XL",
        measurment_unit_id: 2,
        price: 1900,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 49,
        name: "B-Kabab Pizza S",
        measurment_unit_id: 2,
        price: 450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 50,
        name: "B-Kabab Pizza M",
        measurment_unit_id: 2,
        price: 1000,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 51,
        name: "B-Kabab Pizza L",
        measurment_unit_id: 2,
        price: 1300,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 52,
        name: "Kabab Crust M",
        measurment_unit_id: 2,
        price: 1100,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 53,
        name: "Kabab Crust L",
        measurment_unit_id: 2,
        price: 1450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 54,
        name: "Speciel Butter Lazania S",
        measurment_unit_id: 2,
        price: 450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 55,
        name: "Speciel Butter Lazania M",
        measurment_unit_id: 2,
        price: 1100,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 56,
        name: "Speciel Butter Lazania L",
        measurment_unit_id: 2,
        price: 1450,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 61,
        name: "Tikaa Piece",
        measurment_unit_id: 2,
        price: 150,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 62,
        name: "Tikaa Piece Fry",
        measurment_unit_id: 2,
        price: 220,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 63,
        name: "Seekh Kabab",
        measurment_unit_id: 2,
        price: 100,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 67,
        name: "Ragistani Boti",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 72,
        name: "Sadha Roti",
        measurment_unit_id: 2,
        price: 15,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 73,
        name: "Sadha Naan",
        measurment_unit_id: 2,
        price: 30,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 74,
        name: "Roghni Naan",
        measurment_unit_id: 2,
        price: 60,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 76,
        name: "Tandori Paratha",
        measurment_unit_id: 2,
        price: 100,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 79,
        name: "Extra Souce",
        measurment_unit_id: 2,
        price: 30,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 86,
        name: "Sandwich",
        measurment_unit_id: 2,
        price: 400,
        status: "Active",
        category_id: 1,
        image: null,
      },
      {
        id: 89,
        name: "Speciel Butter Lazania XL",
        measurment_unit_id: 2,
        price: 2200,
        status: "Active",
        category_id: 1,
        image: null,
      },
    ],
  },
  {
    id: 2,
    name: "Shawarma",
    sale_items: [
      {
        id: 1,
        name: "Chicken Shawarma",
        measurment_unit_id: 2,
        price: 170,
        status: "Active",
        category_id: 2,
        image: null,
      },
      {
        id: 16,
        name: "Malai Boti Shawarma",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 2,
        image: null,
      },
      {
        id: 18,
        name: "Chicken Cheese Shawarma",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 2,
        image: null,
      },
      {
        id: 19,
        name: "Kabab Shawarma",
        measurment_unit_id: 2,
        price: 170,
        status: "Active",
        category_id: 2,
        image: null,
      },
      {
        id: 20,
        name: "3 in 1 Shawarma",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 2,
        image: "1734722019.png",
      },
      {
        id: 21,
        name: "Naan Shawarma",
        measurment_unit_id: 2,
        price: 350,
        status: "Active",
        category_id: 2,
        image: null,
      },
      {
        id: 90,
        name: "Chicken Platter",
        measurment_unit_id: 2,
        price: 500,
        status: "Active",
        category_id: 2,
        image: null,
      },
    ],
  },
  {
    id: 3,
    name: "Burger",
    sale_items: [
      {
        id: 2,
        name: "Chicken Burger",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 3,
        image: null,
      },
      {
        id: 3,
        name: "Chapli Burger",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 3,
        image: null,
      },
      {
        id: 7,
        name: "Chicken Burger",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 3,
        image: null,
      },
      {
        id: 8,
        name: "Andha Burger",
        measurment_unit_id: 2,
        price: 150,
        status: "Active",
        category_id: 3,
        image: "1734722571.jpg",
      },
      {
        id: 10,
        name: "Petty Burger",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 3,
        image: null,
      },
      {
        id: 12,
        name: "Pizza Burger",
        measurment_unit_id: 2,
        price: 350,
        status: "Active",
        category_id: 3,
        image: null,
      },
    ],
  },
  {
    id: 4,
    name: "Cold Drink",
    sale_items: [
      {
        id: 4,
        name: "Coke 1 L",
        measurment_unit_id: 2,
        price: 160,
        status: "Active",
        category_id: 4,
        image: null,
      },
      {
        id: 5,
        name: "7up Regular",
        measurment_unit_id: 2,
        price: 60,
        status: "Active",
        category_id: 4,
        image: "1734722215.png",
      },
      {
        id: 81,
        name: "coke 1.5 L",
        measurment_unit_id: 2,
        price: 200,
        status: "Active",
        category_id: 4,
        image: null,
      },
      {
        id: 87,
        name: "Coke 0.5 L",
        measurment_unit_id: 2,
        price: 100,
        status: "Active",
        category_id: 4,
        image: null,
      },
    ],
  },
  {
    id: 5,
    name: "Pasta",
    sale_items: [
      {
        id: 30,
        name: "Pasta F1",
        measurment_unit_id: 2,
        price: 350,
        status: "Active",
        category_id: 5,
        image: null,
      },
      {
        id: 31,
        name: "Pasta F2",
        measurment_unit_id: 2,
        price: 700,
        status: "Active",
        category_id: 5,
        image: null,
      },
      {
        id: 88,
        name: "Crunchy Pasta",
        measurment_unit_id: 2,
        price: 400,
        status: "Active",
        category_id: 5,
        image: null,
      },
    ],
  },
  {
    id: 6,
    name: "BBQ",
    sale_items: [
      {
        id: 57,
        name: "Chest Piece",
        measurment_unit_id: 2,
        price: 380,
        status: "Active",
        category_id: 6,
        image: null,
      },
      {
        id: 59,
        name: "Leg Piece",
        measurment_unit_id: 2,
        price: 300,
        status: "Active",
        category_id: 6,
        image: null,
      },
      {
        id: 65,
        name: "Chicken Malai Boti",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 6,
        image: null,
      },
      {
        id: 66,
        name: "Afghani Boti",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 6,
        image: "1734722344.jpg",
      },
      {
        id: 82,
        name: "Beef Kabab",
        measurment_unit_id: 2,
        price: 150,
        status: "Active",
        category_id: 6,
        image: null,
      },
    ],
  },
  {
    id: 7,
    name: "Paratha",
    sale_items: [
      {
        id: 22,
        name: "Chicken Pratha",
        measurment_unit_id: 2,
        price: 220,
        status: "Active",
        category_id: 7,
        image: null,
      },
      {
        id: 25,
        name: "Malai Boti Paratha",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 7,
        image: null,
      },
      {
        id: 26,
        name: "Pizza Paratha",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 7,
        image: null,
      },
      {
        id: 27,
        name: "Chicken Cheese Paratha",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 7,
        image: null,
      },
      {
        id: 28,
        name: "Kabab Paratha",
        measurment_unit_id: 2,
        price: 220,
        status: "Active",
        category_id: 7,
        image: null,
      },
      {
        id: 29,
        name: "3 in 1 Paratha",
        measurment_unit_id: 2,
        price: 280,
        status: "Active",
        category_id: 7,
        image: "1734721612.jpeg",
      },
    ],
  },
  {
    id: 8,
    name: "Fried",
    sale_items: [
      {
        id: 36,
        name: "Pizza Fries",
        measurment_unit_id: 2,
        price: 600,
        status: "Active",
        category_id: 8,
        image: null,
      },
      {
        id: 80,
        name: "Hot wings 10",
        measurment_unit_id: 2,
        price: 500,
        status: "Active",
        category_id: 8,
        image: null,
      },
      {
        id: 83,
        name: "Fries Half",
        measurment_unit_id: 2,
        price: 150,
        status: "Active",
        category_id: 8,
        image: null,
      },
      {
        id: 84,
        name: "Fries Full",
        measurment_unit_id: 2,
        price: 300,
        status: "Active",
        category_id: 8,
        image: null,
      },
    ],
  },
  {
    id: 9,
    name: "Fry",
    sale_items: [
      {
        id: 58,
        name: "Chest Piece Fry",
        measurment_unit_id: 2,
        price: 550,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 60,
        name: "Leg Piece Fry",
        measurment_unit_id: 2,
        price: 500,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 64,
        name: "Chicken Kabab Fry",
        measurment_unit_id: 2,
        price: 170,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 68,
        name: "Chicken Pakoora",
        measurment_unit_id: 1,
        price: 900,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 70,
        name: "Chicken Krhai",
        measurment_unit_id: 1,
        price: 1600,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 71,
        name: "Jhal Faraizi",
        measurment_unit_id: 2,
        price: 550,
        status: "Active",
        category_id: 9,
        image: null,
      },
      {
        id: 85,
        name: "Beef Kabab Fry",
        measurment_unit_id: 2,
        price: 200,
        status: "Active",
        category_id: 9,
        image: null,
      },
    ],
  },
  {
    id: 10,
    name: "Fish",
    sale_items: [
      {
        id: 69,
        name: "Grill Fish",
        measurment_unit_id: 1,
        price: 1300,
        status: "Active",
        category_id: 10,
        image: null,
      },
    ],
  },
  {
    id: 11,
    name: "Tandoor",
    sale_items: [
      {
        id: 75,
        name: "Khameri Roti",
        measurment_unit_id: 2,
        price: 30,
        status: "Active",
        category_id: 11,
        image: null,
      },
      {
        id: 77,
        name: "Keemy Wala Naan",
        measurment_unit_id: 2,
        price: 250,
        status: "Active",
        category_id: 11,
        image: null,
      },
      {
        id: 78,
        name: "Garlic Naan",
        measurment_unit_id: 2,
        price: 100,
        status: "Active",
        category_id: 11,
        image: null,
      },
    ],
  },
];
