'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
// import { store } from "./store/store";
import { Toaster } from "@/components/ui/sonner";
import { Provider } from "jotai";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Provider>
        <div>

         {/* <Provider store={store}> */}
         <Toaster />

        {children}
        {/* </Provider> */}
        </div>
          </Provider>
       
      </body>
    </html>
  );
}
